services:
  image: swift-deploy-1-node:latest
  port: 3000
  mode: canary
  version: 1.0.0
  replicas: 1
  restart_policy: unless-stopped
  log_volume: swiftdeploy-logs
nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30
  contact: ops@swiftdeploy.io
network:
  name: swiftdeploy-net
  driver_type: bridge
